### ISSUE TITLE
How do I input an open-vocabulary text description?

### ISSUE THREAD

**Issue by 123lcy123** [CVRP-SOLE/SOLE#4]
Hello, thank you for developing a good work, i am really interested in it. But I want to know how do I input an open-vocabulary text description like the example you gave?

**Comment by 0nandon** [comment]
Thanks for your interest!

We input the text description in line 166~185 of `models/sole.py`. You may change corresponding part to input your own text query.

Furthermore, if you want to segment masks that is only related to your text query (without segmenting the entire objects in the scene), you con control `CURR_TOPK` parameter in validation bash file. For example, if you set `CURR_TOPK=1`, the model will output one single mask that is most related to your input text query.

**Comment by 123lcy123** [comment]
Thanks for your immediate reply, I will try it later.
