### ISSUE TITLE
About result on Scannet

### ISSUE THREAD

**Issue by hxiaoj** [CVRP-SOLE/SOLE#5]
I select 20 scenes in scannet and evaluate them but get a bad result:

average        :          0.002          0.003          0.006

I don't modify the code and the precomputed featrue, and I use the scripts in the SOLE to process the scannet.

**Comment by CVRP-SOLE** [comment]
Have you tried to evaluate the SOLE on the whole validation dataset?

**Comment by 0nandon** [comment]
Have you tried to evaluate the SOLE on the whole validation dataset?

**Comment by hxiaoj** [comment]
Because of the limited gpu memory, I can't try, but when I test the same 20 scenes in mask3d, the result is right

**Comment by hxiaoj** [comment]
Can you provide your result on 20 scenes? I only add 'self._data = self._data[:20]' in the line 248 of /SOLE/datasets/semseg.py and run the /SOLE/scripts/scannet/scannet_val.sh to get the evaluation result of 20 scenes

**Comment by 0nandon** [comment]
We checked the validation code, and the result is fine in 312 scenes of validation dataset. We will check the result in the selected 20 scenes within this week.

**Comment by 0nandon** [comment]
Hi, we just evaluated our model on first 20 scenes among 312 validation scenes.

<img width="561" alt="스크린샷 2024-07-08 오전 11 26 18" src="https://github.com/CVRP-SOLE/SOLE/assets/71716834/d1e3e92e-6dbd-4d1c-be29-d4d7f04029f7">

Result seems fine. I recommend you to fix `data/processd/scannet/validation_database.yaml` and manually reduce the number of validation scenes.

**Comment by hxiaoj** [comment]
can you detailed descript how manually reduce the number of validation scenes?

**Comment by 0nandon** [comment]
Hi @hxiaoj, and sorry for late reply.

You can simply erase the config of the scene you want to remove in the `data/processd/scannet/validation_database.yaml` file. This file contains the configuration of 312 validation scenes. If you remove configurations of 292 scenes, only 20 scenes will be evaluated.

Furthermore, NVIDIA 3090 GPU(24GB) should be enough to evaluate the whole validation scene.

Best, Seungjun Lee.
