### ISSUE TITLE
Image processing operations

### ISSUE THREAD

**Issue by 1304150468** [CVRP-SOLE/SOLE#7]
Hello, if I want to directly use images to generate per-point clip features, how should I proceed? I haven't found any relevant code for this, or are all image-related operations pre-computed?

**Comment by 0nandon** [comment]
Hi. We precomputed the per-point CLIP features with following OpenScene scheme. You may refer to this [code](https://github.com/pengsongyou/openscene/blob/main/scripts/feature_fusion/scannet_openseg.py) from OpenScene repository.

If images are your own dataset (which are not from ScanNet dataset), you may need the camera parameters for the corresponding images.
