### ISSUE TITLE
 AttributeError: cython_sources

### ISSUE THREAD

**Issue by sailor-z** [CVRP-SOLE/SOLE#8]
Hi,

Thanks for releasing the code. I failed to install the dependency `pyyaml==5.4.1` and I got the error:

 AttributeError: cython_sources
 
I found some solutions by switching to another version like https://github.com/yaml/pyyaml/issues/724#issuecomment-1638591821
 
However, it seems that `volumentations` is not compatible with other versions of pyyaml. Could you please share some information how you managed to handle this problem?

**Comment by 0nandon** [comment]
Thanks for your interest.

You may check this [issue](https://github.com/JonasSchult/Mask3D/issues/121) in the Mask3D repo. It will resolve your issue.

**Comment by sailor-z** [comment]
Thanks for your prompt reply. I have tried this solution, but I got another error after I ran `pip install "cython<3.0.0"`. 
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/0cf546cb-e659-4c8f-9023-188cf5ea396b">

This error occurs when importing pytorch-lightning. I have also tried different versions of lightning, but none of them works.

**Comment by 0nandon** [comment]
Hi @sailor-z, and sorry for the late reply.

We simulated the installation process again and checked that it works fine in our environment. It seems that error is related to `importlib-metadata` library. You may check the version of corresponding library.

Furthermore, check this [post](https://stackoverflow.com/questions/67212594/attributeerror-pathdistribution-object-has-no-attribute-name).

Thanks.
